name: Build and deploy Python project to Azure Function App - Blast-Putting-Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'
  FUNCTION_APP_NAME: 'Blast-Putting-Pipeline'
  RESOURCE_GROUP: 'Blast'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Azure Functions Core Tools
        run: npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3CF7B18563DC4F428D52D622E452F71B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_70A2864C80DE4DBC92407596F8566040 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_58CF43C83C6D4B2095B2127B6F31CDEB }}

      - name: Deploy to Azure Functions
        run: func azure functionapp publish ${{ env.FUNCTION_APP_NAME }} --python
